version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout

     # buildroot
     - run: cd ./docker__buildroot && docker build --no-cache --build-arg USER=$USER -t rubuschl/rpi4-buildroot:123 .
     - run: cd ./docker__buildroot && docker run --rm -ti --user=$USER:$USER --workdir=/home/$USER -v $PWD/dl:/home/$USER/buildroot/dl -v $PWD/output:/home/$USER/buildroot/output rubuschl/rpi4-buildroot:123
